services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: true       # Allows optimizing the container by removing unused services; this also means

    Bash\Bundle\CacheBundle\:
        resource: '../../*'
        exclude: '../src/{DependencyInjection,Kernel.php}'
